### ISSUE TITLE
"Inconsistent Mount" 

### ISSUE THREAD

**Issue by privacyguy123** [snake-4/Zygisk-Assistant#10]
Result in Native Test detector. What exactly does this mean? I thought it only happened when another file was mounted over the top of a system file for example and can be avoided by using mount --bind - I've looked at the code and can't see somewhere where this would be happening?

**Comment by snake-4** [comment]
Could you use the debug build and post the output of this command: `adb logcat ZygiskAssistant/JNI:* *:S`

**Comment by snake-4** [comment]
I'm fairly certain this was fixed in 2.1.0 since bind mounts are unmounted with root privileges now so I don't see how there'd be inconsistent mounts anymore.

**Comment by privacyguy123** [comment]
My problem, ignore!
