### ISSUE TITLE
Issues with playintegrityfix

### ISSUE THREAD

**Issue by soulxaki** [snake-4/Zygisk-Assistant#12]
I tried release and debug, both of them causing issues to playintegrityfix.
Same case with kernelsu

![Without zygisk assistant](https://github.com/snake-4/Zygisk-Assistant/assets/114589854/863907c6-1d01-45fc-922c-44f151d52d63)

![With release](https://github.com/snake-4/Zygisk-Assistant/assets/114589854/d4bf3d01-237d-42ea-8280-3814537ed80f)

![With debug](https://github.com/snake-4/Zygisk-Assistant/assets/114589854/d52da2e4-dfb3-46ea-a2ca-275e8f2a182e)

**Comment by snake-4** [comment]
Please try this build https://github.com/snake-4/Zygisk-Assistant/actions/runs/8713369999/artifacts/1420029812

**Comment by snake-4** [comment]
It should be fixed in 2.1.0
