### ISSUE TITLE
Apps crash after unloading fonts

### ISSUE THREAD

**Issue by kodein1** [snake-4/Zygisk-Assistant#13]
ZA is in conflict with the Font Manager module (app) if I change the original fonts to some other ones...
Then set the restart system UI

And if I have all the modules enabled, then with active ZA, the mobile will turn off into recovery after about 3-5 minutes

**Comment by snake-4** [comment]
Likely very similar to #11. Zygote preloads the fonts and if they're replaced, well, the fork won't see the replacement but will still try to access it.

**Comment by snake-4** [comment]
> Use [FontLoader](https://github.com/HuskyDG/Zygisk-FontLoader)

That's a nice module. I think this can also be solved by changing the font path in memory so that denylisted apps will load the default system fonts.

**Comment by snake-4** [comment]
Closing in favor of #59
