### ISSUE TITLE
TIDE BUSINESS INDIA app detects root in v2.1.0

### ISSUE THREAD

**Issue by thelastbatman** [snake-4/Zygisk-Assistant#14]
After updating to v2.1.0 play store application called 'TIDE BUSINESS INDIA' doesn't work anymore. It detects root on startup and force closes. Switched back to v2.0.4 and it works fine. So a bad release for me. Won't update untill issue is fixed. 

https://play.google.com/store/apps/details?id=co.tide.tideplatform.in

**Comment by snake-4** [comment]
I see but I don't think 2.0.4 would work with this app at all. Are you sure it's not related to the fact that the app was updated a few days ago?

**Comment by thelastbatman** [comment]
> I see but I don't think 2.0.4 would work with this app at all. Are you sure it's not related to the fact that the app was updated a few days ago?

Even i thought so. But after updating to Tide latest version also it works fine on v2.0.4. so its clear v2.1.0 messes something up for this app

**Comment by thelastbatman** [comment]
> Can you post your device details, Android version, Magisk version and module list?
> 
> I've installed this app you've linked and I can confirm that it doesn't work on any version of Zygisk Assistant at the moment.

Device  - Poco f3 gt 
Android - 13 based on Hyper Os 
Magisk - Kitsune delta v27
![Screenshot_2024-04-26-00-22-43-826_snjgql rfw](https://github.com/snake-4/Zygisk-Assistant/assets/90608358/ef9750ac-a154-4af5-921e-bf148d72d69a)
![Screenshot_2024-04-26-00-22-36-581_snjgql rfw](https://github.com/snake-4/Zygisk-Assistant/assets/90608358/ddea0d23-6d0d-4f12-80a9-4071129af210)

**Comment by snake-4** [comment]
I've a theory but I'd need you to confirm it. Could you try disabling lsposed and try both 2.1.0 and 2.0.4?

**Comment by snake-4** [comment]
Refer to #19 for this issue.

**Comment by thelastbatman** [comment]
You said it is lsposed detection fixed in new versions. But still your latest versions 2.1.0 and 2.1.1 doesn't help . Tide app detects magisk on startup. So using version 2.0.4 for now. Please fix this man.

**Comment by thelastbatman** [comment]
> Refer to #19 for this issue.

You said it is lsposed detection fixed in new versions. But still your latest versions 2.1.0 and 2.1.1 doesn't help . Tide app detects magisk on startup. So using version 2.0.4 for now. Please fix this man. Also if lspoded is the culprit then how come app opening on foss 2.0.4?
