### ISSUE TITLE
Youtube ReVanced module isn't working.

### ISSUE THREAD

**Issue by Edgars-Cirulis** [snake-4/Zygisk-Assistant#15]
Hello,

I am writing to inform you that the YouTube ReVanced module is not functioning with the most recent update, version 2.1.0. As a result, I was forced to downgrade to an earlier version in order to continue using the module.

**Comment by snake-4** [comment]
The YouTube app has to be whitelisted in order to "see" the mount of ReVanced. Otherwise it won't see the modifications. On KSU disable unmount and on Magisk remove it from the denylist.

**Comment by Edgars-Cirulis** [comment]
I am using KernelSU and not using any ReVanced Managers, just an module by j-hc https://github.com/j-hc/revanced-magisk-module  There is no whitelist for sure, also disable unmount there's no option like that either, I see only unmout modules by default but it's checked on because it makes more sense by reading the description

**Comment by snake-4** [comment]
`Unmount modules` has to be disabled on YT app for it to work. Otherwise it unmounts your ReVanced module from YT.

**Comment by Edgars-Cirulis** [comment]
> `Unmount modules` has to be disabled on YT app for it to work. Otherwise it unmounts your ReVanced module from YT.

By default "Unmount modules" is enabled on KSU, without this Zygisk Assistant module YouTube ReVanced works completely fine.

**Comment by snake-4** [comment]
> > `Unmount modules` has to be disabled on YT app for it to work. Otherwise it unmounts your ReVanced module from YT.
> 
> By default "Unmount modules" is enabled on KSU, without this Zygisk Assistant module YouTube ReVanced works completely fine.  

https://kernelsu.org/guide/app-profile.html#umount-modules

See the link above for the purpose of that option. This module uses the value of that option to determine whether to unmount the modules or not.

If your kernel is not GKI and KSU was improperly ported, then it won't have an effect at all by itself.
