### ISSUE TITLE
Creating Mount Root Detection 

### ISSUE THREAD

**Issue by tech2surface** [snake-4/Zygisk-Assistant#18]
Device Name:- Poco X5 Pro 5G(Redwood)
ROM:- Matrix OS
OS:- Android 14(QPR2)
ROOT  MANAGER:- Kernel SU(11807)

1. After Installing Zygisk Assistant(v2.10):-

    Modules Used:- Zygisk Assistant, Shaimiko, 
                                Zygisk Map Hide, 
                                Lsposed Mod(No Log), Zygisk 
                                NXT(EnforceList Disabled), 
                                Safetynet Sensetive Props V5

   Root Detected In:- Hunter(5.5.0) 
![Screenshot_20240427-153854_Hunter](https://github.com/snake-4/Zygisk-Assistant/assets/95482053/d1146074-35ad-48ae-9094-acbf6b1aa415)

2. Before Installing Zygisk Assistant:-
 
    Modules Used:- Shaimiko, 
                                Zygisk Map Hide, 
                                Lsposed Mod(No Log), Zygisk 
                                NXT(EnforceList Disabled), 
                                Safetynet Sensetive Props V5

![Screenshot_20240427-154148_Hunter](https://github.com/snake-4/Zygisk-Assistant/assets/95482053/6af0bd52-13f9-4ea5-b38b-52f33677fd80)

**Comment by snake-4** [comment]
That's LSPosed! I'll see if I can hide LSPosed in the next version.

**Comment by snake-4** [comment]
Refer to #19 for this issue.

**Comment by brian6932** [comment]
`2.1.1` gives me the following. Weird app, I don't even have Magisk installed, I guess it notices KSU as well.
![](https://github.com/snake-4/Zygisk-Assistant/assets/18603393/8e6cf35b-9f9f-4fa2-bd92-a0c5c8b7ca3e)
