### ISSUE TITLE
Hide ext4 flag errors=remount-ro

### ISSUE THREAD

**Issue by snake-4** [snake-4/Zygisk-Assistant#2]
Compared to stock kernel, Magisk adds `errors=remount-ro` to all `userdata` mounts.
Should we remount them without the flag? It may be an unreliable detection vector but it's still an abnormality.

Magisk patched kernel:
`/dev/block/bootdevice/by-name/userdata on /data type ext4 (rw,seclabel,nosuid,nodev,noatime,nobarrier,noauto_da_alloc,errors=remount-ro,data=ordered)`

Stock kernel:
`/dev/block/bootdevice/by-name/userdata on /data type ext4 (rw,seclabel,nosuid,nodev,noatime,nobarrier,noauto_da_alloc,data=ordered)`

**Comment by snake-4** [comment]
This only seems to happen when there's a bind mount module is present.

**Comment by privacyguy123** [comment]
I use bind mounts to avoid other detector apps - you wouldn't consider this change?

**Comment by snake-4** [comment]
> I use bind mounts to avoid other detector apps - you wouldn't consider this change? 

Bind mounts are already hidden since 2.0.3 but this specific trace is not hidden. Though I guess most apps don't check this trace because it's kind of unreliable and may also happen on a stock device.

**Comment by snake-4** [comment]
Implemented in f200aa4.
