### ISSUE TITLE
Zygote crashes with HyperCeiler

### ISSUE THREAD

**Issue by ZIFEIYU3zifeiyu** [snake-4/Zygisk-Assistant#20]
![Screenshot_2024-04-28-02-12-56-771_me.weishu.kernelsu.jpg](https://github.com/snake-4/Zygisk-Assistant/assets/127037295/638ca693-8d8f-4c3e-a142-1f9fc15887ae)

![Screenshot_2024-04-28-02-13-04-577_me.weishu.kernelsu.jpg](https://github.com/snake-4/Zygisk-Assistant/assets/127037295/5b7defb8-ed24-4bcd-90a9-9e43cac070c0)

**Comment by snake-4** [comment]
Can you post the details of your device and try these steps?
1. Install https://github.com/snake-4/Zygisk-Assistant/actions/runs/8861260538/artifacts/1453513497
2. Disable LSPosed
3. Send the output of `adb logcat ZygiskAssistant/JNI:* Zygote:* ZygiskNext:* *:E`

**Comment by ZIFEIYU3zifeiyu** [comment]
There might be some conflict with LSPosed or my Xposed's module, when I close LSPosed and restart it many times, Zygisk Next still works fine, but when I open LSPosed, I have to execute adb logcat ZygiskAssistant/JNI:* Zygote:* before each restart.ZygiskNext:* *:E command before each reboot to ensure that Zygisk Next will work every time, otherwise it will still stop most likely.![Screenshot_2024-04-28-04-06-37-274_bin.mt.plus.canary.jpg](https://github.com/snake-4/Zygisk-Assistant/assets/127037295/5cef41af-e421-4f02-a0e1-47ba6540a6df)

If this is not the way the command is used, then I may not have fully understood it, and that would mean that the above inference may be wrong, please understand that I don't know anything about this.

**Comment by ZIFEIYU3zifeiyu** [comment]
> Can you post the details of your device and try these steps?
> 1. Install https://github.com/snake-4/Zygisk-Assistant/actions/runs/8861260538/artifacts/1453513497
> 2. Install version 1.0.4 of ZygiskNext
> 3. Disable LSPosed
> 4. Send the output of `adb logcat ZygiskAssistant/JNI:* Zygote:* ZygiskNext:* *:E`

There might be some conflict with LSPosed or my Xposed's module, when I close LSPosed and restart it many times, Zygisk Next still works fine, but when I open LSPosed, I have to execute adb logcat ZygiskAssistant/JNI:* Zygote:* before each restart.ZygiskNext:* *:E command before each reboot to ensure that Zygisk Next will work every time, otherwise it will still stop most likely.![Screenshot_2024-04-28-04-06-37-274_bin.mt.plus.canary.jpg](https://github.com/snake-4/Zygisk-Assistant/assets/127037295/07377455-5d0c-4b41-bdbb-a51eae72e9c5)

If this is not the way the command is used, then I may not have fully understood it, and that would mean that the above inference may be wrong, please understand that I don't know anything about this.

**Comment by snake-4** [comment]
Okay and can you post your LSPosed module list? Maybe I can try to install them myself and see what the issue is.

**Comment by ZIFEIYU3zifeiyu** [comment]
> Okay and can you post your LSPosed module list? Maybe I can try to install them myself and see what the issue is.

Of course. I'm sorry for the trouble.![Screenshot_2024-04-28-14-16-30-504_com.android.shell.jpg](https://github.com/snake-4/Zygisk-Assistant/assets/127037295/a9abbaef-0c36-462e-94c9-982d2e53dfbb)

**Comment by snake-4** [comment]
I'm not sure to be honest. Can you try disabling your LSPosed modules to see which one causes it?

**Comment by ZIFEIYU3zifeiyu** [comment]
> I'm not sure to be honest. Can you try disabling your LSPosed modules to see which one causes it?

There may be a conflict with the module hyperceiler, when I close it and restart three times, zygisk next works fine, when I start it and uncheck the system framework as a scope and restart three times, zygisk next still works fine

**Comment by snake-4** [comment]
Right. After installing the debug build of this module with HyperCeiler enabled, can you try to run this command on your PC? `adb logcat > log.txt`

USB debugging has to be enabled on your phone.

After you ran the command, please upload `log.txt` here.

**Comment by ZIFEIYU3zifeiyu** [comment]
> Right. After installing the debug build of this module with HyperCeiler enabled, can you try to run this command on your PC? `adb logcat > log.txt`
> 
> USB debugging has to be enabled on your phone.
> 
> After you ran the command, please upload `log.txt` here.

![log.txt](https://github.com/snake-4/Zygisk-Assistant/files/15174162/log.txt)

**Comment by aviraxp** [comment]
casued by lsposed.

**Comment by snake-4** [comment]
Right, it looks like it's failing to call the `getAttributeValue` hook callback in Java.
@ZIFEIYU3zifeiyu Could you check if this also happens with Shamiko? Also try sending logs while using the [latest debug build](https://github.com/snake-4/Zygisk-Assistant/actions?query=is%3Asuccess).

**Comment by aviraxp** [comment]
This is due to a bug in lsposed, not related to the module. No public fix yet.
