### ISSUE TITLE
Some apps crash

### ISSUE THREAD

**Issue by Mostafaobaid** [snake-4/Zygisk-Assistant#21]
Using kitsune + zygisk assistant everything is fine except instapay app it opens once then crashes
With magisk alpha + shamiko + zygisk assistant  instapay crashes and some apps crash randomly like google play

**Comment by snake-4** [comment]
So the problem only happens when used with Magisk Alpha and Shamiko? Could you post a list of your modules and your device details?

**Comment by Mostafaobaid** [comment]
No 
With kitsune only instapay app crashes 
But with alpha+shamiko instapay crashes and random apps like Whatsapp and google play...
random apps only crash once then it work normal many times then crash once and work many times
I'm on evolution x ROM a13
My modules:
Skvalex call recorder 
Systemless hosts
Lsposed 
Play integrity fix
Safetynet sensitive props 
Zygisk maphide
Shamiko (in case of alpha)

**Comment by snake-4** [comment]
Could you install the debug build of this module with Magisk Alpha and Shamiko, then upload the logs after an app other than instapay crashes?

`adb logcat > log.txt` on your PC.

**Comment by Mostafaobaid** [comment]
[Uploading log.txt…]()

**Comment by Mostafaobaid** [comment]
[log.txt](https://github.com/snake-4/Zygisk-Assistant/files/15157131/log.txt)

**Comment by snake-4** [comment]
So `/data` is getting unmounted and it's not caused by this module. I don't know whether Magisk Alpha or Shamiko is doing that, but neither of them have logs so it's not possible to tell what exactly is going on.

Maybe try to ask their developers?
