### ISSUE TITLE
Won't be able to work with BootloaderSpoofer?

### ISSUE THREAD

**Issue by scruel** [snake-4/Zygisk-Assistant#25]
**Describe the bug**
https://github.com/chiteroman/BootloaderSpoofer
After applied this to momo & hunter, zygisk will be detected.

**Steps To Reproduce**

1. Install momo/huter, enable Zygisk-Assistant, reboot
2. Open BootloaderSpoofer, select momo/huter app.
3. Open momo & hunter, you will see results.

Detection apk files:
[Detect.zip](https://github.com/snake-4/Zygisk-Assistant/files/15214059/Detect.zip)

**Context**

 - Device: Xiaomi cas
 - OS: Android 13
 - Version of Magisk, KSU or APatch: Apatch 10763
 - Other Root Module(s): Zygisk-Next-1.0.5, LSPosed-v1.9.3_mod-7244-zygisk
 - LSPosed Module(s): None

**Comment by snake-4** [comment]
Well, if you inject an Xposed module to an app, it will be able to detect that. There's not much we can do about that as the injected modules will reside in the address space of the target app.

**Comment by ThePedroo** [comment]
> Well, if you inject an Xposed module to an app, it will be able to detect that. There's not much we can do about that as the injected modules will reside in the address space of the target app.

You are right, however Shamiko is able to hide it from Momo, where Zygisk Assistant fails. I am unsure if that's the case for the OP though, but it is for me.

Should I open a new issue or only send a logcat here?

**Comment by snake-4** [comment]
> > Well, if you inject an Xposed module to an app, it will be able to detect that. There's not much we can do about that as the injected modules will reside in the address space of the target app.
> 
> You are right, however Shamiko is able to hide it from Momo, where Zygisk Assistant fails. I am unsure if that's the case for the OP though, but it is for me.
> 
> Should I open a new issue or only send a logcat here?

No. Momo has outdated detection methods. Injected Xposed modules are always detectable even with Shamiko.

**Comment by ThePedroo** [comment]
That is a rather controversial statement, as Momo is still one of the best apps to detect rooting.

Even if we agree with "it outdated detection methods", it would still be neat to patch those detection methods, don't you agree?
