### ISSUE TITLE
LSPosed mod still detected

### ISSUE THREAD

**Issue by scruel** [snake-4/Zygisk-Assistant#29]
**Describe the bug**

mywalkb/LSPosed_mod_v1.9.3_7289 + Apatch_v10772 is still detectable by nullptr's Native Test, still getting "Evil Service" even with zygisk_assistant_v2.1.1_8c1d7f5.

Excluded Native Test app on Apatch, follow excluded disable on Zygisk_Next_v1.5.0_305_d463cbb

Xiaomi cas, hyperos official, Android 13

**Logcat**
[APatch_bugreport_2024-03-25_15_23.tar.gz](https://github.com/snake-4/Zygisk-Assistant/files/15268485/APatch_bugreport_2024-03-25_15_23.tar.gz)

**Comment by snake-4** [comment]
Can you report this to LSposed mod devs instead? I have no plans of hiding services. We're only hiding the mounts of LSPosed.

**Comment by scruel** [comment]
LSPosed itself already has built-in hide features...

**Comment by DanGLES3** [comment]
> **Describe the bug**
> 
> mywalkb/LSPosed_mod_v1.9.3_7289 + Apatch_v10772 is still detectable by nullptr's Native Test, still getting "Evil Service" even with zygisk_assistant_v2.1.1_8c1d7f5.
> 
> Excluded Native Test app on Apatch, follow excluded disable on Zygisk_Next_v1.5.0_305_d463cbb
> 
> Xiaomi cas, hyperos official, Android 13
> 
> **Logcat** [APatch_bugreport_2024-03-25_15_23.tar.gz](https://github.com/snake-4/Zygisk-Assistant/files/15268485/APatch_bugreport_2024-03-25_15_23.tar.gz)

From my experience only this fork of Lsposed doesn't seem to cause Evil Service detection 

https://github.com/pumPCin/LSPosed_mod/actions

**Comment by scruel** [comment]
@DanGLES3 Yeap, his LSposed as well, it won't be detected yet:
https://github.com/pumPCin/LSPosed/actions

I already tried them, BTW thank you for mention it here!
