### ISSUE TITLE
Microsoft company portal detected root

### ISSUE THREAD

**Issue by atsukokita** [snake-4/Zygisk-Assistant#30]
![Screenshot_2024-05-10-13-47-29-792_com microsoft teams-edit](https://github.com/snake-4/Zygisk-Assistant/assets/106592670/1020a4ca-06ac-46fe-a00d-80b52cca41a3)
![Screenshot_2024-05-10-13-47-29-792_com microsoft teams-edit](https://github.com/snake-4/Zygisk-Assistant/assets/106592670/af52ee76-4c17-409b-a0c1-7dbf8b039c18)

**Describe the bug**

**Steps To Reproduce**

1. 
2. 
3. 

**Context**

 - Device: 
 - OS: 
 - Version of Magisk, KSU or APatch: 
 - Other Root Module(s): None
 - LSPosed Module(s): None

**Logcat**

**Comment by snake-4** [comment]
Try to fill out the issue template.
