### ISSUE TITLE
pubg newstate detecting magisk

### ISSUE THREAD

**Issue by rajarshikhatua100** [snake-4/Zygisk-Assistant#31]
https://play.google.com/store/apps/details?id=com.pubg.newstate this app is detecting root, I am on magisk 27

**Context**
 - Device: Samsung m31
 - OS: Android 13
 - Version of Magisk, KSU or APatch: magisk 27
 - Other Root Module(s):  PlayIntegrityNEXT
 - LSPosed Module(s): core patch

**Comment by snake-4** [comment]
Might be similar to #28. There's too little information here to go on as you didn't fill in the issue template. Make sure to try with Magisk Manager uninstalled as well.
