### ISSUE TITLE
Zygisk next 1.0.5 on Apatch has some errors 

### ISSUE THREAD

**Issue by Geovanne5** [snake-4/Zygisk-Assistant#32]
When I installed the zygisk assistant module with zygisk next 1.0.5 the momo tectacao application recognized "found magisk" but with zygisk 1.0.4 this does not happen
![Screenshot_20240513_150513_Momo](https://github.com/snake-4/Zygisk-Assistant/assets/151881793/472c4638-dda2-4c8a-a56f-f1fdf6ade5e3)

**Comment by snake-4** [comment]
Fill out the issue template please.

**Comment by Geovanne5** [comment]
When I install the zygisk assistant module with zygisk next 1.0.5 in Momo it appears "found magisk" but when I install the zygisk assistant with zygisk next 1.0.4 this problem is resolved and the message "found magisk" no longer appears no momo
