### ISSUE TITLE
Does ZA run with LineageOS for microG or /e/OS?

### ISSUE THREAD

**Issue by bege10** [snake-4/Zygisk-Assistant#33]
Hello,
I have a Shiftphone 6mq with /e/OS (based on LineageOS for microG), Android 13
Magisk 27.0
LSPosed 1.9.2

Is ZA supposed to work with this system?

![Screenshot_20240514-224837_Yet Another SafetyNet Attestation Checker](https://github.com/snake-4/Zygisk-Assistant/assets/1184237/ef362e10-e2bd-4699-9c05-9821895fce2f)

**Comment by snake-4** [comment]
Yes and it won't help you pass Play Integrity on it's own cause you have to change the build fingerprint as well. You can use PlayIntegrityFix for that.

**Comment by bege10** [comment]
With PlayIntegrityFix it doesn't work either. Because `uname -r` shows `4.9.337-lineage+`?
The Play Integrity API Checker shows this error:
![Screenshot_20240515-130743_Play Integrity API Checker](https://github.com/snake-4/Zygisk-Assistant/assets/1184237/8f123ec8-5730-41bd-bf24-bda352dd661a)
SafetyNet is activated in microG but it comes with Fake Store to replace real Play Store.

**Comment by snake-4** [comment]
Play Integrity, as the name implies, is an API on the Play Store app. MicroG doesn't implement it so there's nothing to do about that. https://github.com/microg/GmsCore/issues/1771
