### ISSUE TITLE
Zygisk detected by SingPass Mobile

### ISSUE THREAD

**Issue by donald-ong** [snake-4/Zygisk-Assistant#38]
Please help to check if possible. Thank you.

https://play.google.com/store/apps/details?id=sg.ndi.sp&hl=en

**Comment by snake-4** [comment]
I'm closing some issues in favor of this: #24

**Comment by rmnscnce** [comment]
For `sg.ndi.sp` you should look into [Hide My Applist](https://github.com/Dr-TSNG/Hide-My-Applist) to hide apps that are detected by the app as threats.

**Comment by donald-ong** [comment]
I have tested it. It does not work. :(
