### ISSUE TITLE
Australian apps root detection

### ISSUE THREAD

**Issue by danielgruber8** [snake-4/Zygisk-Assistant#39]
The following AU apps are detected in official Magisk debug version 27002 (81658d45) with Zygisk, Zygisk Assistant, Shamiko, LSPosed Mod, PlayIntegrity Chiteroman, Playcurl. All latest versions.

com.bp.mobile.bpme.aus
au.com.unisuper

**Comment by snake-4** [comment]
A similar issue is being tracked and since there's more discussion going on there, I'll close this for now.
