### ISSUE TITLE
Magisk Systemless Hosts is detected

### ISSUE THREAD

**Issue by snake-4** [snake-4/Zygisk-Assistant#4]
Very likely to be the same issue as #2.

Don't use the built-in Systemless Hosts in Magisk.
Use a module that does overlay mount instead.

Perhaps https://github.com/symbuzzer/systemless-hosts-KernelSU-module/ would work on Magisk?

**Comment by snake-4** [comment]
> Does the proposed alternative work?

Yes.

I'm not sure if Shamiko does something special to hide bind mounts but I don't think so.

**Comment by AK2H** [comment]
So it's not a flaw in design of your module, but rather an undiscovered trace from **Magisk Systemless Hosts** which no one found out before so it was never adressed by **Shamiko**

If so, I guess we can keep using the default module since it's not known to be causing detections.

**Comment by snake-4** [comment]
> So it's not a flaw in design of your module, but rather an undiscovered trace from **Magisk Systemless Hosts** which no one found out before, thus it was never adressed by **Shamiko**.
> 
> If so, I guess we can keep using the default module since it's not known to be causing detection problems.
> 
> The only way it was discovered is because of the abnormalities **Magisk** was producing.

I've just checked with Shamiko and the abnormality is still there. So yeah you could say that.

I can try to implement a method to hide this unexpected change caused by Magisk.

The reason why I closed this issue is because there's a better detailed issue which I referenced in the first comment here.

**Comment by AK2H** [comment]
Absolutely!
I saw the earlier open issue.
The reason I asked the question is because you made a recommendation in a closed issue, so I just wanted to clarify some things.
