### ISSUE TITLE
Problem with Youtube Revanced

### ISSUE THREAD

**Issue by animetrom** [snake-4/Zygisk-Assistant#40]
**Describe the bug**
When I install Youtube Revanced from RVX Repo, it just doesn't work.
I tried to deactivate the module, it was normal, however, when reactivating the module it simply returned to normal YouTube.

**Steps To Reproduce**

1. I disabled module
2. Flash RVX Lite YT
3. When reactivating the module and restarting, Youtube returns without the patch applied.

**Context**

 - Device: POCO X5 Pro (redwood)
 - OS: crDroid 10.5 (A14)
 - Version of Magisk, KSU or APatch: APatch
 - Other Root Module(s): None
 - LSPosed Module(s): None

**Comment by snake-4** [comment]
https://github.com/snake-4/Zygisk-Assistant/issues/15#issuecomment-2076482842
