### ISSUE TITLE
ReVanced mods broken after Zygisk Assistant install

### ISSUE THREAD

**Issue by eddie-LA** [snake-4/Zygisk-Assistant#43]
**Describe the bug**

Zygisk Assistant breaks YT ReVanced mods. After installing the assistant zip and rebooting YT has ads and it's extra mod settings are missing. Disabling the assistant and rebooting makes ReVanced mods behave properly once again at the cost of root being detected by Company Portal. 

Note: Using Shamiko instead worked fine - didn't break the mods and hid root. 

**Steps To Reproduce**

1. Install latest YT and YTM ReVanced zips
2. Reboot
3. Use YT and YTM, they work fine
4. Try using any MS apps requiring Company Portal, it shows "device is rooted" 
5. Install Zygisk Assistant 
6. Reboot
7. YT/YTM now have ads and they look like normal YT/YTM. The mod seems inactive/broken after Zygisk Assistant has been installed. Probably somewhere the mount breaks? 
8. Disabling Zygisk Assistant and rebooting solves the issues with the YT/YTM mod but Company Portal once again detects root. 

**Context**

 - Device: Nothing Phone 2
 - OS: Stock, version 2.5.5 (latest) with arter kernel
 - Version of Magisk, KSU or APatch: KSU 1.0, 11838
 - Other Root Module(s): YT ReVanced, YT Music ReVanced, Zygisk detach, PlayIntegrityFix
 - LSPosed Module(s): None

**Logcat**

**Comment by snake-4** [comment]
https://github.com/snake-4/Zygisk-Assistant/issues/15#issuecomment-2076482842
Disable unmount modules for YT and YTM.
