### ISSUE TITLE
Root / Zygisk is detected by Klivvr Egypt.

### ISSUE THREAD

**Issue by keosh1** [snake-4/Zygisk-Assistant#45]
Describe the bug
Root / Zygisk is detected by Klivvr Egypt.
app link :
https://play.google.com/store/apps/details?id=com.klivvr.consumer&hl=en&gl=US

Steps To Reproduce

Install Latest Stable Apatch(V10763)

Exclude klivvr app from SuperUser
Install zygisk LSposed Mod, YT REvanced by j-hc, Zygisk next official,and ur module tho xD .
Try to launch klivvr but detect root.
i have another 3 bank apps after exclude them works fine except klivvr 
Context

Device: Poco F5 Pro
OS: A14 Xiaomi EU Dev
Version of Magisk, KSU or APatch: Aptach (V10763)
Other Root Module(s):
Zygisk LSposed Mod
YT REvanced by j-hc
Zygisk next
LSPosed Module(s):
bootloader spoofing 
SnapEnhance
Thanox 
fuck for vip

[klivvr.zip](https://github.com/user-a
![photo_2024-06-10_21-39-59](https://github.com/snake-4/Zygisk-Assistant/assets/106485828/9689933e-cf5e-4de3-b5cb-7d7681d2c54e)
![photo_2024-06-10_21-40-05](https://github.com/snake-4/Zygisk-Assistant/assets/106485828/f62755ce-b34f-44a2-a796-bd50c44aed90)
ttachments/files/15777747/klivvr.zip)

**Comment by keosh1** [comment]
[klivvr.zip](https://github.com/user-attachments/files/15777800/klivvr.zip)

**Comment by keosh1** [comment]
How can i use root then !!

**Comment by DanGLES3** [comment]
> How can i use root then !!

Then set up, Lsposed and use hidemyapplist. The app is detecting the apatch app.

**Comment by keosh1** [comment]
> > How can i use root then !!
> 
> Then set up Lsposed and use hidemyapplist. The app is detecting the apatch app.

I try to use hide my app and hide apatch and hide my app too and add them to klivvr and nothing changes

**Comment by snake-4** [comment]
> > > How can i use root then !!
> > 
> > 
> > Then set up Lsposed and use hidemyapplist. The app is detecting the apatch app.
> 
> I try to use hide my app and hide apatch and hide my app too and add them to klivvr and nothing changes

I don't have time to look into this app but try disabling lsposed and uninstalling apatch app temporarily to see if that fixes it. If it is app detection, I'll close this issue.

**Comment by keosh1** [comment]
I try to use hide my app and hide apatch and hide my app too and add them to klivvr and nothing changes 
Still detect it after all this

**Comment by snake-4** [comment]
I've checked the app. It has a check for the manager app so you have to uninstall apatch app. Also try without lsposed if it still doesn't work after uninstalling it.
