### ISSUE TITLE
Difference with BypassRootCheckPro?

### ISSUE THREAD

**Issue by devnoname120** [snake-4/Zygisk-Assistant#46]
There is a similar project on GitHub: https://github.com/gauravssnl/BypassRootCheckPro

How does Zygisk-Assistant compare to it in terms of features and completeness? Thanks

**Comment by DanGLES3** [comment]
The main issue Xposed modules will always have is they'll never be truly able to hide the fact they're injected into the app's process, that by itself greatly exposes any Xposed modules 

Also this module doesn't seem to do anything that other root hiding solutions don't already do, it only does them in arguably the worst way possible (injecting into the app's process)
