### ISSUE TITLE
Problem with app using RootBeer

### ISSUE THREAD

**Issue by N3F0S** [snake-4/Zygisk-Assistant#47]
Hi,

I can't use apps using RootBeer to check if the device is rooted. I tried the RootBeer checker and i have an issue on the SE Linux Flag. Do you know if is it possible to implement something to hide root frome apps using the RootBeer method?

Thank you very much for your work

Rémi

**Comment by snake-4** [comment]
RootBeer SELinux check is broken. SELinux will be enabled on any CTS compliant ROM.
