### ISSUE TITLE
FrameworkPatch Crashes/Hangs Android

### ISSUE THREAD

**Issue by KBapna** [snake-4/Zygisk-Assistant#49]
**Describe the bug**

When installing FrameworkPatch (https://github.com/chiteroman/FrameworkPatch/tree/69e08eff494b68ccd3ec71ffb04e0a798d7c686e) from FrameworkPatcherGO (https://github.com/changhuapeng/FrameworkPatcherGO) with Zygisk-Assistant, the system crashes. However, upon disabling the Zygisk-Assistant module, Android starts responding normally.

1. Enabled **only** Zygisk-Assistant with Zygisk-Next: Android functions normally.
2. Enabled **only** FrameworkPatcherGO with Zygisk-Next: Android functions normally.
3. Enabled **all three** (Zygisk-Assistant, FrameworkPatcherGO, and Zygisk-Next): Android crashes or hangs.

**All modules except Zygisk-Assistant, FrameworkPatcherGO, and Zygisk-Next were disabled during testing**

**Steps To Reproduce**

1.  Install Zygisk-Next and Zygisk-Assistant. Reboot
2. Install FrameworkPatcherGo (All options Yes. Tried different combinations, Output is same). Reboot
3. Android starts freezing.

**Context**

 - Device: Redmi K30 (Phoenix) 
 - OS: Bliss OS (Android 14)
 - Version of Magisk, KSU or APatch: KSU v1.0.0
 - Other Root Module(s): None
 - LSPosed Module(s): None

**Logcat**

[logcat_output.txt](https://github.com/user-attachments/files/15919846/logcat_output.txt)

**Comment by snake-4** [comment]
Same issue as this one: https://github.com/changhuapeng/FrameworkPatcherGO/issues/12

This can't be easily fixed by this module. Even if I add an exception for this module, it will then result in a mount that is detectable. The module's dev has to figure out a solution.
