### ISSUE TITLE
Lsposed zygisk error

### ISSUE THREAD

**Issue by hunterscop1** [snake-4/Zygisk-Assistant#5]
My lsposed zygisk got the error after installing this module

**Comment by snake-4** [comment]
Can you add your Android, Magisk and LSPosed version and a list of modules that you have?

Could you also post the error you get?

**Comment by hunterscop1** [comment]
Nah, I'm just switching to magisk from kernelsu and the lsposed working
perfectly fine

**Comment by snake-4** [comment]
Does that mean there's no error now?

**Comment by hunterscop1** [comment]
Yes, it works!
