### ISSUE TITLE
Interbank detects root

### ISSUE THREAD

**Issue by parasiteoflife** [snake-4/Zygisk-Assistant#50]
**Describe the bug**
Interbank still detects root when using the module.  
This is the app: https://play.google.com/store/apps/details?id=pe.com.interbank.mobilebanking

**Context**

 - Device: Mi A3
 - OS: LineageOS 21
 - Version of Magisk, KSU or APatch: Magisk official v27
 - Other Root Module(s): microG Installer Revived
 - LSPosed Module(s): NoStorageRestrict, XPL-EX (Interbank app is not enabled in any of the modules)

**Comment by snake-4** [comment]
Seems to work fine on my end. Try disabling LSPosed
