### ISSUE TITLE
Doesnt hide LSposed zygisk injection

### ISSUE THREAD

**Issue by DiscordUserGuy** [snake-4/Zygisk-Assistant#51]
**Describe the bug**

Does not hide [LSPosed_mod](https://github.com/mywalkb/LSPosed_mod) zygisk injection
**Steps To Reproduce**

1. Use latest stable release of [apatch](https://github.com/bmax121/APatch/releases/tag/10763) at this time.
2. Install latest stable zygiskNEXT [release](https://github.com/Dr-TSNG/ZygiskNext/releases/tag/v1.0.6-2) at this time.
3. Install latest stable [LSPosed_mod](https://github.com/mywalkb/LSPosed_mod/releases) at this time.
4. Download and Install [Native Detector 5.9 apk](https://t.me/reveny1/50)
5. Do not apply any LSposed modules to native detector.
6. Open Native detector

**Context**

 - Device: Redmi note 12 4g Topaz
 - OS: Android 14
 - Version of Magisk, KSU or APatch: Apatch 10762
 - Other Root Module(s):  Pixel Launcher Mods Overlay, 17.4 iOs Emoji font, Zygisk Next, Zygisk-LSPosed and Cherish Peekaboo 1.3 kpm
 - LSPosed Module(s): Hide My Applist, NoStorageRestrict, SnapEnhance and TGRAMHOOKS

**Comment by DJLeleX** [comment]
> **Describe the bug**
> 
> Does not hide [LSPosed_mod](https://github.com/mywalkb/LSPosed_mod) zygisk injection **Steps To Reproduce**
> 
> 1. Use latest stable release of [apatch](https://github.com/bmax121/APatch/releases/tag/10763) at this time.
> 2. Install latest stable zygiskNEXT [release](https://github.com/Dr-TSNG/ZygiskNext/releases/tag/v1.0.6-2) at this time.
> 3. Install latest stable [LSPosed_mod](https://github.com/mywalkb/LSPosed_mod/releases) at this time.
> 4. Download and Install [Native Detector 5.9 apk](https://t.me/reveny1/50)
> 5. Do not apply any LSposed modules to native detector.
> 6. Open Native detector
> 
> **Context**
> 
> * Device: Redmi note 12 4g Topaz
> * OS: Android 14
> * Version of Magisk, KSU or APatch: Apatch 10762
> * Other Root Module(s):  Pixel Launcher Mods Overlay, 17.4 iOs Emoji font, Zygisk Next, Zygisk-LSPosed and Cherish Peekaboo 1.3 kpm
> * LSPosed Module(s): Hide My Applist, NoStorageRestrict, SnapEnhance and TGRAMHOOKS

Also on KernelSU and with orginal LSPosed (and [pumPCin's fork](https://github.com/pumPCin/LSPosed) )

I tried with both latest stable and latest build from actions with all three LSPosed version (orginal, pumPCin and mywalkb)

**Comment by snake-4** [comment]
LSPosed service detection should be fixed by LSP itself, not this module.

**Comment by DJLeleX** [comment]
> LSPosed service detection should be fixed by LSP itself, not this module.

Yeah I tought so, I just wanted to share the info.
Thanks!

**Comment by DJLeleX** [comment]
> Injection will be detected if you enable any LSPosed module, no matter which module

It is detected even if no module is active inside LSPosed, but LSPosed itself is active.
Is there anything you'd recommend to "solve" this issue (besides not using LSPosed..)?

**Comment by DJLeleX** [comment]
> Sorry, you mean evil service 0x2? 🙃

I guess so.
