### ISSUE TITLE
temp root loss magisk alpha and leftover files even after removing module.

### ISSUE THREAD

**Issue by AlexS2412** [snake-4/Zygisk-Assistant#52]
**Describe the bug**

**Steps To Reproduce**

1. 
2. 
3. 

**Context**

 - Device: 
 - OS: 
 - Version of Magisk, KSU or APatch: 
 - Other Root Module(s): None
 - LSPosed Module(s): None

**Logcat**

**Comment by snake-4** [comment]
What?
