### ISSUE TITLE
Fix "Maybe Zygisk Assistant is Installed" in Native Detector.

### ISSUE THREAD

**Issue by AlexS2412** [snake-4/Zygisk-Assistant#53]
**Describe the bug**
if you run the assistant, it messes with kernel and other files, creating a purposeful detection in the root checker. this is unethical. please fix this.

**Steps To Reproduce**

1.  run native detector app
2.  see that zygisk assistant is detected on purpose
3. ask "why am i okay with this?"

**Context**

 - Device: Any
 - OS: Android 14
 - Version of Magisk, KSU or APatch: Magisk Alpha
 - Other Root Module(s): N/A
 - LSPosed Module(s): N/A

**Logcat**
N/A

![Screenshot_20240704-000855~2](https://github.com/snake-4/Zygisk-Assistant/assets/14182708/2098c0bf-d2d7-4362-bcda-31c305efafc4)

**Comment by snake-4** [comment]
> if you run the assistant, it messes with kernel and other files, creating a purposeful detection in the root checker. this is unethical. please fix this.

This is not the case. In fact, the code is open-source and you can see that there are no modifications to files nor the kernel.

Also, I can't reproduce this with Magisk 27003 and stock Zygisk. Maybe try that? Also make sure you're not using the debug build if there is a detection.
