### ISSUE TITLE
一加6T-lineageos-18.1-kernelsu-0.9.4 刷了assistant疯狂重启，卡lineageos启动页面，黑屏

### ISSUE THREAD

**Issue by xyychenchen** [snake-4/Zygisk-Assistant#54]
**Describe the bug**

**Steps To Reproduce**

1. 
2. 
3. 

**Context**

 - Device: 
 - OS: 
 - Version of Magisk, KSU or APatch: 
 - Other Root Module(s): None
 - LSPosed Module(s): None

**Logcat**

**Comment by snake-4** [comment]
Attach logs, will you? I don't see why it wouldn't work on LOS 18.1
