### ISSUE TITLE
[Feature Req] way to configure app list when using ZygiskNext with Magisk

### ISSUE THREAD

**Issue by HemanthJabalpuri** [snake-4/Zygisk-Assistant#55]
**Describe the bug**

Currently, I am using ZygiskNext with Magisk for better Zygisk hiding from a bank application in called "Yono SBI". With this setup, we need to disable inbuilt Zygisk and which leads to greyed-out "Configure DenyList".

Currently we can use `magisk --denylist add PKG` to "Configure DenyList" even when Zygisk is turned off.

Is there any better way to do the same?

**Steps To Reproduce**

1. Install Magisk
2. Disable Zygisk
3. Install ZygiskNext
4. Try to use "Configure DenyList" in Magisk app

**Context**

 - Device: Moto G52
 - OS: 13
 - Version of Magisk, KSU or APatch: Magisk v27.0(27000)
 - Other Root Module(s): ZygiskNext
 - LSPosed Module(s): None

**Logcat**

N.A

**Comment by snake-4** [comment]
I think you can temporarily toggle Zygisk on, configure the apps and disable it again. You won't have to reboot the phone this way.

I don't think there's an easy way to implement this as ZygiskNext does not support Web UI in Magisk. In fact, Magisk does not have a Web UI functionality.
