### ISSUE TITLE
Fingerprint scanner broken after 2.1.2 on oneplus 8t

### ISSUE THREAD

**Issue by fgjaee** [snake-4/Zygisk-Assistant#58]

**Comment by snake-4** [comment]
Could you share your firmware version? I will check it. 

@osm0sis are you aware of something like this?

**Comment by osm0sis** [comment]
Awesome let's figure out why

**Comment by osm0sis** [comment]
It'll be similar to the ones already in the boot_completed area of service.sh

**Comment by osm0sis** [comment]
To troubleshoot the user can start by commenting them out until they figure out which is the issue, then we can move them around to get the timing right

**Comment by fgjaee** [comment]
> Could you share your firmware version? I will check it.
> 
> @osm0sis are you aware of something like this?

![Screenshot_2024-08-03-11-27-01-69_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/31a2ad4d-7100-41c4-8a2e-c6afde62efa6)

**Comment by fgjaee** [comment]
> > Could you share your firmware version? I will check it.
> > 
> > @osm0sis are you aware of something like this?
> 
> ![Screenshot_2024-08-03-11-27-01-69_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/31a2ad4d-7100-41c4-8a2e-c6afde62efa6)
> 

Uninstalling the module and reinstalling then disabling scripts only mode in PIFork and rebooting fixed the issue.

**Comment by osm0sis** [comment]
I'll flash my 8T with OOS to see if I can reproduce the issue... Show me your modules list?

**Comment by osm0sis** [comment]
I flashed KB2005_14.0.0.601(EX01) on my NA variant 8T and I can't reproduce the issue at all...

I enrolled my thumbprint, flashed ZA 2.1.2 and rebooted, no issue unlocking with my thumb. Flashed PIFork #258 just to see if having 2 scripts doing the same thing would make any difference, and still no issue unlocking with my thumb. 

Not sure what to tell you. 🤔🤷‍♂️

**Comment by qnorsten** [comment]
I am ruunning KB2003_14.0.0.601(EX01) with my Oneplus 8T and finger print sensor works fine here (was not working until you added the sleep back)
