### ISSUE TITLE
Hide /system/addon.d ?

### ISSUE THREAD

**Issue by Magniquick** [snake-4/Zygisk-Assistant#61]
All my apps do work, but momo does detect my custom rom
It seems like it relies on [/system/addon.d](https://www.reddit.com/r/Magisk/comments/ulmxhh/comment/i7x4mai/), so would be nice if this could hide it : D

**Comment by osm0sis** [comment]
You can't "hide" a directory...

**Comment by snake-4** [comment]
The directory cannot be hidden without the use of overlays and overlays themselves are detectable. What you can do is delete the folder via a root shell at the cost of losing functionality.

In theory, it is possible to hide overlays as well but that is too much work for something insignificant.
