### ISSUE TITLE
Breaks app

### ISSUE THREAD

**Issue by Shidapu** [snake-4/Zygisk-Assistant#63]
Breaks the following app: https://github.com/chenxiaolong/BCR/issues/586#event-13933101885

 - Device:  Samsung Fold 3 
 - OS:  A14, OneUi6
 - Version of Magisk 27000

**Comment by Shidapu** [comment]
> Nothing is unmounted unless the target app is in the deny list. Make sure that the app is not in the deny list.

Alright, thanks. Its not in the deny list. Maybe the issue lies with tricky_store then.

**Comment by Shidapu** [comment]
Just for info if someone needs the solution in the future, install BCR with module. Right after, extract the apk from the module zip file and update the BCR application with the extracted apk file.

**Comment by snake-4** [comment]
Could you confirm if removing everything from the deny list and disabling TS fixes the problem? In that scenario the app should be visible to launchers and all other apps.

**Comment by Shidapu** [comment]
> Could you confirm if removing everything from the deny list and disabling TS fixes the problem? In that scenario the app should be visible to launchers and all other apps.

No need to remove the list in deny list. Simly Disabling TS fixed the issue. But o found a real solution to the problem mentioned above.
