### ISSUE TITLE
Kotak neo detects zygisk

### ISSUE THREAD

**Issue by satishreddy07** [snake-4/Zygisk-Assistant#65]
https://play.google.com/store/apps/details?id=com.kotak.neo&hl=en_IN&pli=1

this is the app link
whatever you do its detects zygisk

**Comment by Zerogoki00** [comment]
I can confirm, I have:
Magisk 27006
Shamiko 1.1.1
Zygisk Assistant 2.1.3
Tricky Story with unrevoked keybox
Hide my Applist

But this app still detects Magisk no matter what

**Comment by snake-4** [comment]
> I can confirm, I have: Magisk 27006 Shamiko 1.1.1 Zygisk Assistant 2.1.3 Tricky Story with unrevoked keybox Hide my Applist
> 
> And I pass all checks in Momo app.
> 
> Device is Pixel 7 Pro with stock Android 13
> 
> But this app still detects Magisk no matter what

Could you also try with ZygiskNext?

**Comment by Zerogoki00** [comment]
> Could you also try with ZygiskNext?

I tried and it still detects root.

**Comment by snake-4** [comment]
Works fine on my end with ZygiskNext and Magisk. Though it treats developer options as root.

**Comment by qyzhaojinxi** [comment]
@Zerogoki00 Hi bro,how to bypass all in momo? I also tried these but now work.
