### ISSUE TITLE
Zygisk Assistant Conflicts with ReVanced Magisk Module on KernelSU

### ISSUE THREAD

**Issue by Louis-htmlcss** [snake-4/Zygisk-Assistant#67]
**Describe the bug**
When using the Zygisk Assistant module with KernelSU (KSU), the ReVanced Magisk module by j-hc (https://github.com/j-hc/revanced-magisk-module) doesn't work properly. With the module installed, I only have access to the free version of the app, even though I should have the premium version.

**Steps To Reproduce**
1. Install KernelSU on the device
2. Install Zygisk Assistant module
3. Install ReVanced Magisk module by j-hc (from https://github.com/j-hc/revanced-magisk-module)
4. Open the youtube ReVanced app
5. Observe that only free features are available instead of premium

**Context**

 - Device: [Your device model]
 - OS: [Your Android version]
 - Version of Magisk, KSU or APatch: KernelSU 1.0.1
 - Other Root Module(s): Zygisk Assistant, ReVanced Magisk module by j-hc, lsposed
 - LSPosed Module(s): snapenhance

**Logcat**

[Attach logcat file if available]

**Comment by snake-4** [comment]
"Unmount modules" has to be disabled for the YouTube app from the KSU manager. Otherwise the ReVanced module is unmounted.
![image](https://github.com/user-attachments/assets/f3d85d0b-ce79-4c22-b172-0f5009467b9c)

**Comment by Louis-htmlcss** [comment]
> "Unmount modules" has to be disabled for the YouTube app from the KSU manager. Otherwise the ReVanced module is unmounted.
> ![image](https://github.com/user-attachments/assets/f3d85d0b-ce79-4c22-b172-0f5009467b9c)
> 

Thanks it's working fine !
