### ISSUE TITLE
Revanced not working

### ISSUE THREAD

**Issue by timeholder0** [snake-4/Zygisk-Assistant#68]
Revanced is capable of installing the root version of a patch but the bind isn't done leaving the patched apk as stock, when this module is disabled, the apk instantly works.

**Steps To Reproduce**
1. patch any app with the root method of revanced manager
2. open the app or reboot and open the app
3. the app works as stock the patches are not working

**Context**

 - Device: poco f5
 - OS: android 13
 - Version of Magisk, KSU: KSU 11838
 - Other Root Module(s): Zygisk next, play integrity fix
 - LSPosed Module(s): None

**Comment by snake-4** [comment]
This was answered in #15 #43 #40 #67. See the comment https://github.com/snake-4/Zygisk-Assistant/issues/67#issuecomment-2318583225
