### ISSUE TITLE
Not working for CIMB OCTO

### ISSUE THREAD

**Issue by 9M2PJU** [snake-4/Zygisk-Assistant#69]
Describe the bug
CIMB OCTO still detects root when using the module.
This is the app: https://play.google.com/store/apps/details?id=com.cimb.cimbocto&hl=en-US

Context

Device: Poco F5
OS: Miui 13 Minimal Mod
Version of Magisk, KSU or APatch: Magisk official v27008
Other Root Module(s): LSposed
LSPosed Module(s): WA enhancer, GPS setter, hyperceilar

**Comment by snake-4** [comment]
Try without LSPosed and make sure that you pass Play Integrity. It works fine on my end.
