### ISSUE TITLE
not work with Revanced Youtube 

### ISSUE THREAD

**Issue by ask9027** [snake-4/Zygisk-Assistant#70]
**Describe the bug**

**Steps To Reproduce**

1. Install ZygiskNext + ZygiskAssistance 
2. Install Revanced Manager 
3. now patch youtube and open, it dont work
4. but if i reomve ZygiskNext or ZygsikAssistance (one of them or both) then Revanced works

**Context**

 - Device: Mi 11 Lite 4G
 - OS: Android 13
 - Version of KSU: 11872
 - Other Root Module(s): None
 - LSPosed Module(s): None

**Logcat**

[log.txt](https://github.com/user-attachments/files/17074220/log.txt)
i dont know why it is 3MB 😀

**Comment by snake-4** [comment]
https://github.com/snake-4/Zygisk-Assistant/issues/67#issuecomment-2318583225

**Comment by palexdev** [comment]
Sorry to comment on this closed issue but it still refuses to work on my device. 

- Device: OnePlus 12R
- OS: Android 14
- Version of KSU: 11928
- KernelSU Module(s):  [1](https://github.com/user-attachments/assets/96095820-39b1-4134-a216-5f0833b08574), [2](https://github.com/user-attachments/assets/141e968b-640d-49f9-b2df-b8b8439602f9), [3](https://github.com/user-attachments/assets/5d1447b9-3627-4b17-a556-3b6f6c1e5338)
- LSPosed Module(s): NoStorageRestrict, HMA

[YouTube Setup](https://github.com/user-attachments/assets/2993b0bf-eea2-47a1-a7cb-7f68205043fb)
[YT Music Setup](https://github.com/user-attachments/assets/db36117a-bcd6-4c60-a994-95f9b11bc7a7)

Do you need logs? (logcat or KSU eventually?)

**Comment by DanGLES3** [comment]
> Sorry to comment on this closed issue but it still refuses to work on my device.
> 
> * Device: OnePlus 12R
> * OS: Android 14
> * Version of KSU: 11928
> * KernelSU Module(s):  [1](https://github.com/user-attachments/assets/96095820-39b1-4134-a216-5f0833b08574), [2](https://github.com/user-attachments/assets/141e968b-640d-49f9-b2df-b8b8439602f9), [3](https://github.com/user-attachments/assets/5d1447b9-3627-4b17-a556-3b6f6c1e5338)
> * LSPosed Module(s): NoStorageRestrict, HMA
> 
> [YouTube Setup](https://github.com/user-attachments/assets/2993b0bf-eea2-47a1-a7cb-7f68205043fb) [YT Music Setup](https://github.com/user-attachments/assets/db36117a-bcd6-4c60-a994-95f9b11bc7a7)
> 
> Do you need logs? (logcat or KSU eventually?)

You need to add YouTube to the superuser/root list so ZygiskAssistant knows not to unmount Revanced to it

**Comment by palexdev** [comment]
> > Sorry to comment on this closed issue but it still refuses to work on my device.
> > 
> > * Device: OnePlus 12R
> > * OS: Android 14
> > * Version of KSU: 11928
> > * KernelSU Module(s):  [1](https://github.com/user-attachments/assets/96095820-39b1-4134-a216-5f0833b08574), [2](https://github.com/user-attachments/assets/141e968b-640d-49f9-b2df-b8b8439602f9), [3](https://github.com/user-attachments/assets/5d1447b9-3627-4b17-a556-3b6f6c1e5338)
> > * LSPosed Module(s): NoStorageRestrict, HMA
> > 
> > [YouTube Setup](https://github.com/user-attachments/assets/2993b0bf-eea2-47a1-a7cb-7f68205043fb) [YT Music Setup](https://github.com/user-attachments/assets/db36117a-bcd6-4c60-a994-95f9b11bc7a7)
> > 
> > Do you need logs? (logcat or KSU eventually?)
> 
> You need to add YouTube to the superuser/root list so ZygiskAssistant knows not to unmount Revanced to it

You mean like this?
![Screenshot_2024-11-14-20-21-38-68_baaa51257c82a8b3f281ce09e6f2493f.jpg](https://github.com/user-attachments/assets/8c8555cb-ff94-40f0-9679-f52c0787fea5)
