### ISSUE TITLE
Yuh detects root since its last update (1.30.10)

### ISSUE THREAD

**Issue by devnoname120** [snake-4/Zygisk-Assistant#71]
**Describe the bug**

On launch [Yuh](https://play.google.com/store/apps/details?id=com.yuh) 1.30.10 detects root, shows a warning message, and stops.

The last known version that didn't detect root with Zygisk Assistant enabled was [Yuh 1.30.4](https://apk.support/download-app/com.yuh/385/1.30.4).

**Steps To Reproduce**

1. Install [Yuh](https://play.google.com/store/apps/details?id=com.yuh).
2. In KernelSU, activate unmounting modules on this app.
3. Run it.
4. Yuh shows a warning about root and then stops.

**Context**

 - Device: Xiaomi Mi Note 10 Lite (toco)
 - OS: 
 - Version of Magisk, KSU or APatch: KernelSU
 - Other Root Module(s):
   - ZygiskNext 1.1.0
   - LSPosed 1.9.3_mod
 - LSPosed Module(s):
   - Hide My Applist .2.r414.1b2a52e

All other apps work fine and don't detect root.

**Comment by gabriel20xx** [comment]
I also have this issue

**Comment by gabriel20xx** [comment]
It's working again for me after hiding the app list with the "hide my applist" lsposed module and reinstalling the app from play store

**Comment by devnoname120** [comment]
Can confirm Yuh 1.31.0 works fine with KernelSU + Zygisk Assistant v2.1.3 + Hide My Applist 3.3 and the following configuration:

![Screenshot_20241008-213128](https://github.com/user-attachments/assets/3c5d00c6-ecc9-4faf-a6a3-8f5f3c91d0c5)

![Screenshot_20241008-213139](https://github.com/user-attachments/assets/005e86ec-5a9b-4a63-8035-2895c7fd676f)

**Comment by gabriel20xx** [comment]
As I found out, the app must be installed from play store to work

**Comment by devnoname120** [comment]
> As I found out, the app must be installed from play store to work

Thanks for the heads-up! Note that this can be faked with some Magisk module, forgot which

**Comment by devnoname120** [comment]
@gabriel20xx Here is a module that fakes the installation origin of all apps to the Play Store: https://github.com/Pixel-Props/BetterKnownInstalled

**Comment by Crashdummyy** [comment]
Is yuh still working for you ?
I use Yuri keyboxmanager to pass safetynets.
Beides there are no further modules ( besides the dependent playintegrity fix and trickystore ).

I cant get passt the root check

**Comment by devnoname120** [comment]
I switched to an iPhone since then

**Comment by M1scer** [comment]
I am also looking for a solution. Yuh reports that it was installed from an untrusted source.
I use the “BetterKnownInstalled” module to spoof the source.

However, I have not yet managed to get it to accept this. Does anyone have any ideas?
