### ISSUE TITLE
Add hide/spoof for selinux status

### ISSUE THREAD

**Issue by ellordAbdo** [snake-4/Zygisk-Assistant#73]
I have an app that doesn't open when my selinux status is permissive so can you add a hide for selinux state or spoof its status to make the app think my selinux status is enforcing without changing the actual selinux status of the phone(permissive).

**Comment by DanGLES3** [comment]
Any app with decent Selinux detection won't be tricked by a spoofed status as its trivial to detect Selinux in several ways as it leaves huge security gaps apps can poke around to figure out it isn't working (enforcing)
