### ISSUE TITLE
Hexpatch?

### ISSUE THREAD

**Issue by VisionR1** [snake-4/Zygisk-Assistant#74]
Hi, thanks you for this module.
I read inside in this module: sensitive-props-v6.4.8.4
Say this:
Undetectable property deletion:** Utilizes a `hexpatch` method for deleting properties, making it undetectable by SafetyNet. This method was necessary due to limitations in the `magiskboot` applet, and despite requests for improvement, the maintainer ([`topjohnwu on issue 8315`](https://github.com/topjohnwu/Magisk/issues/8315)) opted not to introduce a proper fix.

And because you know better, is a good feature? 
Have any advantage, to put it in your module?
Or maybe you have some similar already.

Sorry if already have, and I didn't notice.

**Comment by snake-4** [comment]
This module doesn't use magiskboot nor hexpatch.
