### ISSUE TITLE
PlayIntegrityFix seems to stop working

### ISSUE THREAD

**Issue by PlatFlat** [snake-4/Zygisk-Assistant#8]
Seems to break Play Integrity specifically MEETS_DEVICE_INTEGRITY when using [PlayIntegrityFix](https://github.com/chiteroman/PlayIntegrityFix) and Zygisk-Assistant

**Comment by irresistibl** [comment]
> Seems to break Play Integrity specifically MEETS_DEVICE_INTEGRITY when using [PlayIntegrityFix](https://github.com/chiteroman/PlayIntegrityFix) and Zygisk-Assistant

This is definitely problematic given the intentions of this module

**Comment by snake-4** [comment]
PlayIntegrityFix v15.9.7 seems to work fine with this module on my device on both Magisk 27.0 and KernelSU.
Can you please try with the latest Magisk version? Also post your Android and Magisk versions.
