### ISSUE TITLE
Dolby atmos module incompatibility

### ISSUE THREAD

**Issue by Leonelus** [snake-4/Zygisk-Assistant#9]
The dolby atmos module stops working after enabling zygisk assistant, pretty much just like how it breaks when zygisk's denylist is enabled

**Comment by snake-4** [comment]
Which Magisk version are you using? If yours has a whitelist, some apps including your launcher have to be whitelisted for that module to work.

**Comment by Leonelus** [comment]
Hello, I followed the installation instructions you provided and it seems to have worked fine, now Dolby Atmos is only unusable if I restart the device and I don't start it up, but it gets fixed as soon as I start the device.

I was actually using apatch instead of magisk, so it's nice to see that the instructions worked out fine anyways, thank you for the help
